# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestAWS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestAWS
  pod 'Gallery', :git => 'https://github.com/hyperoslo/Gallery.git'
  pod 'AWSS3'
  pod 'AWSCore'

end


